Changed Typing for League Entries endpoint
In the typing the Entries endpoint is called via kayn.League.Entries.bySummonerId(id), however in the LeagueEntriesEndpointV4  it is defined as Entries.by.summonerID(id).
This leads to: 
TypeError: kayn.League.Entries.bySummonerID is not a function